#!/usr/bin/env python3
"""Render/check MCP and skill API indexes from the ToolSpec contract."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from hwpx_mcp_server.tool_contract import (  # noqa: E402
    BASELINE_TOOL_SPECS,
    DOMAIN_SPECS,
    TOOL_SPECS,
    bound_tool_registry,
    classification_counts,
    contract_hash,
    contract_payload,
    skill_required_tool_names,
)


def render_markdown() -> str:
    specs = {spec.name: spec for spec in TOOL_SPECS}
    bound = bound_tool_registry().by_name()
    lines = [
        "# HWPX FastMCP Tool Contract",
        "",
        "> Generated by `hwpx-mcp-server/scripts/render_tool_contract.py`. Do not edit by hand.",
        f"> Contract hash: `{contract_hash()}` · default: "
        f"{sum(spec.profile == 'default' for spec in TOOL_SPECS)} · advanced total: {len(TOOL_SPECS)}",
        f"> Baseline classification: `{json.dumps(classification_counts(), sort_keys=True)}`",
        "",
        "The installed plugin exposes the `default` profile. Set `HWPX_MCP_ADVANCED=1` before server import",
        "to add the tools marked `advanced`. `skill-required` tools are startup-health hard requirements.",
        "",
    ]
    for domain in DOMAIN_SPECS:
        lines.extend(
            [
                f"## {domain.title} (`{domain.key}`)",
                "",
                domain.intent,
                "",
                "| Tool | Lifecycle | Profile | Mutates | Schema | Replacements | Skill requirement |",
                "|---|---|---|---|---|---|---|",
            ]
        )
        for name in domain.tools:
            spec = specs[name]
            required = "required" if spec.skill_required else "—"
            replacements = ", ".join(f"`{item}`" for item in spec.replacement_tools) or "—"
            schema_raw = json.dumps(
                {
                    "input": bound[name].input_schema,
                    "output": bound[name].output_schema,
                },
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            )
            schema_hash = hashlib.sha256(schema_raw.encode("utf-8")).hexdigest()[:12]
            lines.append(
                f"| `{name}` | `{spec.classification.value}` | `{spec.profile.value}` | "
                f"{'yes' if spec.mutates else 'no'} | `{schema_hash}` | {replacements} | {required} |"
            )
        lines.append("")
    internal = [spec for spec in BASELINE_TOOL_SPECS if not spec.installed]
    lines.extend(
        [
            "## Internal fixture QA removals",
            "",
            "These names remain importable from their CI libraries but are absent from the installed FastMCP contract.",
            "",
        ]
    )
    lines.extend(f"- `{spec.name}`" for spec in internal)
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_json() -> str:
    payload = contract_payload()
    payload["contractHash"] = contract_hash()
    payload["defaultToolCount"] = sum(spec.profile == "default" for spec in TOOL_SPECS)
    payload["advancedToolCount"] = len(TOOL_SPECS)
    payload["baselineToolCount"] = len(BASELINE_TOOL_SPECS)
    payload["classificationCounts"] = classification_counts()
    payload["skillRequiredTools"] = sorted(skill_required_tool_names())
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def _sync(path: Path, content: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == content:
        print(f"ok: {path}")
        return True
    if check:
        print(f"drift: {path}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote: {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--mcp-output", type=Path, default=ROOT / "docs" / "tool-contract.md")
    parser.add_argument(
        "--mcp-json-output",
        type=Path,
        default=ROOT / "docs" / "tool-contract.generated.json",
    )
    parser.add_argument("--skill-root", type=Path, default=ROOT.parent / "hwpx-skill")
    parser.add_argument("--skip-skill", action="store_true")
    args = parser.parse_args()

    targets = [
        (args.mcp_output, render_markdown()),
        (args.mcp_json_output, render_json()),
    ]
    if not args.skip_skill:
        if not args.skill_root.is_dir():
            if args.check:
                print(f"skill root missing: {args.skill_root}", file=sys.stderr)
                return 1
        else:
            targets.extend(
                [
                    (args.skill_root / "references" / "tool-contract.generated.md", render_markdown()),
                    (args.skill_root / "references" / "tool-contract.generated.json", render_json()),
                ]
            )
    return 0 if all(_sync(path, content, check=args.check) for path, content in targets) else 1


if __name__ == "__main__":
    raise SystemExit(main())
